[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Restrict audits to only main app entry points
    audit_url = [
      "/",
      "/index.html"
    ]