[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Exclude legacy.html from Lighthouse checks
  [plugins.inputs]
    ignore = [
      "/legacy.html"
    ]