name: Apply files from issues

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # Only run when the issue title starts with [files]
    if: startsWith(github.event.issue.title, '[files]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Parse code blocks and write files
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const body = context.payload.issue.body || '';

            // Expect code blocks like: ```file:src/path/File.tsx ... ```
            const regex = /```file:([^\n]+)\n([\s\S]*?)```/g;
            let m, count = 0;
            while ((m = regex.exec(body)) !== null) {
              const filePath = m[1].trim().replace(/^\.?\//,'');
              const content = m[2];
              const abs = path.join(process.cwd(), filePath);
              fs.mkdirSync(path.dirname(abs), { recursive: true });
              fs.writeFileSync(abs, content, 'utf8');
              core.info(`Wrote ${filePath}`);
              count++;
            }
            core.setOutput('count', String(count));

      - name: Create Pull Request
        if: steps.parse.outputs.count != '0'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Apply files from issue #${{ github.event.issue.number }}"
          title: "Apply files from issue #${{ github.event.issue.number }}"
          body: "Automated PR from issue #${{ github.event.issue.number }}."
          branch: "chatgpt/apply-files-${{ github.run_id }}"
          base: "main"
          labels: "bot"

      # Optional: auto-merge (enable 'Allow auto-merge' in repo settings first)
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
