name: Apply files directly to main from issues

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write

jobs:
  apply:
    # Only run if the issue title starts with [files] AND the issue author is the repo owner
    if: startsWith(github.event.issue.title, '[files]') && github.event.issue.user.login == github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Parse code blocks and write files
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const body = context.payload.issue.body || '';

            // Parse blocks like: ```file:path/to/File.tsx\n...content...\n```
            const regex = /```file:([^\n]+)\n([\s\S]*?)```/g;
            let m, count = 0;
            while ((m = regex.exec(body)) !== null) {
              const filePath = m[1].trim().replace(/^\.?\//,'');
              const content = m[2];
              const abs = path.join(process.cwd(), filePath);
              fs.mkdirSync(path.dirname(abs), { recursive: true });
              fs.writeFileSync(abs, content, 'utf8');
              core.info(`Wrote ${filePath}`);
              count++;
            }
            core.setOutput('count', String(count));

      - name: Commit & push to main
        if: steps.parse.outputs.count != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Apply files from issue #${{ github.event.issue.number }}"
          git push origin HEAD:main
