name: Apply files from issue

on:
  issues:
    types: [opened, edited, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # Run only if title contains [files] OR the issue has a label named files
    if: contains(github.event.issue.title, '[files]') || contains(join(github.event.issue.labels.*.name, ','), 'files')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse issue body and write files
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const body = context.payload.issue.body || '';
            const re = /```file:([^\n]+)\n([\s\S]*?)```/g;
            let m, count = 0;
            while ((m = re.exec(body)) !== null) {
              const filePath = m[1].trim();
              const content = m[2].replace(/\r\n/g, '\n');
              const dir = path.dirname(filePath);
              fs.mkdirSync(dir, { recursive: true });
              fs.writeFileSync(filePath, content);
              core.info(`Wrote ${filePath}`);
              count++;
            }
            if (count === 0) core.setFailed('No ```file:...``` blocks found in issue body');

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Apply files: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}"
          commit-message: "apply(files): #${{ github.event.issue.number }} – ${{ github.event.issue.title }}"
          body: "Auto-generated from issue #${{ github.event.issue.number }} by workflow."
          branch: "files/issue-${{ github.event.issue.number }}"
          delete-branch: true
          base: "main"
